# Generated by Django 4.2.16 on 2026-08-24 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_api_otpreco_identif_idx_otp_lookup_idx_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE api_invoiceitem ADD COLUMN IF NOT EXISTS hsn_code varchar(20) NOT NULL DEFAULT '';",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="ALTER TABLE api_invoiceitem ADD COLUMN IF NOT EXISTS mrp numeric(10,2) NOT NULL DEFAULT 0;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="ALTER TABLE api_product ADD COLUMN IF NOT EXISTS hsn_code varchar(20) NOT NULL DEFAULT '';",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="ALTER TABLE api_product ADD COLUMN IF NOT EXISTS mrp numeric(10,2) NOT NULL DEFAULT 0;",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
