# Generated by Django 4.2.16 on 2026-09-05 17:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_invoiceitem_hsn_code_invoiceitem_mrp_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='invoiceitem',
                    name='hsn_code',
                    field=models.CharField(blank=True, max_length=20),
                ),
                migrations.AddField(
                    model_name='invoiceitem',
                    name='mrp',
                    field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                migrations.AddField(
                    model_name='product',
                    name='hsn_code',
                    field=models.CharField(blank=True, max_length=20),
                ),
                migrations.AddField(
                    model_name='product',
                    name='mrp',
                    field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
                ),
            ],
            database_operations=[],
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('partial', 'Partial'), ('credit', 'Credit'), ('refunded', 'Refunded')], default='paid', max_length=10),
        ),
    ]
