# Generated by Django 4.2.16 on 2026-09-07 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def normalize_legacy_values(apps, schema_editor):
    Invoice = apps.get_model('api', 'Invoice')
    Invoice.objects.filter(balance_due__lt=0).update(balance_due=0)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_invoiceitem_cost_price_invoiceitem_hsn_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('invoice', 'Invoice Debit'), ('payment', 'Payment Credit'), ('sales_return', 'Sales Return'), ('credit_adjustment', 'Credit Adjustment'), ('debit_adjustment', 'Debit Adjustment')], max_length=30)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reference_type', models.CharField(blank=True, max_length=50)),
                ('reference_id', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SupplierLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('purchase', 'Purchase Debit'), ('payment', 'Payment Credit'), ('purchase_return', 'Purchase Return'), ('credit_adjustment', 'Credit Adjustment'), ('debit_adjustment', 'Debit Adjustment')], max_length=30)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reference_type', models.CharField(blank=True, max_length=50)),
                ('reference_id', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='movement_key',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.RunPython(normalize_legacy_values, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.CheckConstraint(check=models.Q(('credit_limit__gte', 0)), name='customer_credit_limit_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.CheckConstraint(check=models.Q(('outstanding_amount__gte', 0)), name='customer_outstanding_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='customerpayment',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='customer_payment_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='inventorytransaction',
            constraint=models.CheckConstraint(check=models.Q(('quantity', 0), _negated=True), name='inventory_quantity_nonzero'),
        ),
        migrations.AddConstraint(
            model_name='inventorytransaction',
            constraint=models.CheckConstraint(check=models.Q(('before_stock__gte', 0)), name='inventory_before_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='inventorytransaction',
            constraint=models.CheckConstraint(check=models.Q(('after_stock__gte', 0)), name='inventory_after_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='inventorytransaction',
            constraint=models.CheckConstraint(check=models.Q(('unit_cost__gte', 0), ('unit_cost__isnull', True), _connector='OR'), name='inventory_unit_cost_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(check=models.Q(('subtotal__gte', 0)), name='invoice_subtotal_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(check=models.Q(('discount_amount__gte', 0)), name='invoice_discount_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(check=models.Q(('tax_amount__gte', 0)), name='invoice_tax_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(check=models.Q(('grand_total__gte', 0)), name='invoice_total_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(check=models.Q(('paid_amount__gte', 0)), name='invoice_paid_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(check=models.Q(('balance_due__gte', 0)), name='invoice_balance_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='invoiceitem',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gt', 0)), name='invoice_item_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='invoiceitem',
            constraint=models.CheckConstraint(check=models.Q(('unit_price__gte', 0)), name='invoice_item_price_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='invoiceitem',
            constraint=models.CheckConstraint(check=models.Q(('cost_price__gte', 0)), name='invoice_item_cost_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='invoiceitem',
            constraint=models.CheckConstraint(check=models.Q(('discount_percent__gte', 0), ('discount_percent__lte', 100)), name='invoice_item_discount_valid'),
        ),
        migrations.AddConstraint(
            model_name='invoiceitem',
            constraint=models.CheckConstraint(check=models.Q(('gst_percent__gte', 0), ('gst_percent__lte', 100)), name='invoice_item_gst_valid'),
        ),
        migrations.AddConstraint(
            model_name='invoiceitem',
            constraint=models.CheckConstraint(check=models.Q(('total__gte', 0)), name='invoice_item_total_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='payment_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(check=models.Q(('mrp__gte', 0)), name='product_mrp_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(check=models.Q(('purchase_price__gte', 0)), name='product_purchase_price_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(check=models.Q(('selling_price__gte', 0)), name='product_selling_price_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(check=models.Q(('gst_percent__gte', 0), ('gst_percent__lte', 100)), name='product_gst_valid'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(check=models.Q(('current_stock__gte', 0)), name='product_stock_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(check=models.Q(('minimum_stock__gte', 0)), name='product_minimum_stock_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='purchaseitem',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gt', 0)), name='purchase_item_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='purchaseitem',
            constraint=models.CheckConstraint(check=models.Q(('purchase_price__gte', 0)), name='purchase_item_price_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='purchaseitem',
            constraint=models.CheckConstraint(check=models.Q(('gst_percent__gte', 0), ('gst_percent__lte', 100)), name='purchase_item_gst_valid'),
        ),
        migrations.AddConstraint(
            model_name='purchaseitem',
            constraint=models.CheckConstraint(check=models.Q(('total__gte', 0)), name='purchase_item_total_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.CheckConstraint(check=models.Q(('outstanding_amount__gte', 0)), name='supplier_outstanding_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='supplierpayment',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='supplier_payment_amount_positive'),
        ),
        migrations.AddField(
            model_name='supplierledger',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.business'),
        ),
        migrations.AddField(
            model_name='supplierledger',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplierledger',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='api.supplier'),
        ),
        migrations.AddField(
            model_name='customerledger',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.business'),
        ),
        migrations.AddField(
            model_name='customerledger',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customerledger',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='api.customer'),
        ),
        migrations.AddConstraint(
            model_name='supplierledger',
            constraint=models.CheckConstraint(check=models.Q(('debit__gte', 0)), name='supplier_ledger_debit_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='supplierledger',
            constraint=models.CheckConstraint(check=models.Q(('credit__gte', 0)), name='supplier_ledger_credit_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='supplierledger',
            constraint=models.CheckConstraint(check=models.Q(('debit', 0), ('credit', 0), _connector='OR'), name='supplier_ledger_one_sided'),
        ),
        migrations.AddConstraint(
            model_name='customerledger',
            constraint=models.CheckConstraint(check=models.Q(('debit__gte', 0)), name='customer_ledger_debit_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='customerledger',
            constraint=models.CheckConstraint(check=models.Q(('credit__gte', 0)), name='customer_ledger_credit_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='customerledger',
            constraint=models.CheckConstraint(check=models.Q(('debit', 0), ('credit', 0), _connector='OR'), name='customer_ledger_one_sided'),
        ),
    ]
