# Generated by Django 4.2.16 on 2026-09-07 08:49

from django.db import migrations, models


def seed_opening_balances(apps, schema_editor):
    Customer = apps.get_model('api', 'Customer')
    CustomerLedger = apps.get_model('api', 'CustomerLedger')
    Supplier = apps.get_model('api', 'Supplier')
    SupplierLedger = apps.get_model('api', 'SupplierLedger')

    for customer in Customer.objects.filter(outstanding_amount__gt=0):
        CustomerLedger.objects.get_or_create(
            event_key=f'opening:customer:{customer.pk}',
            defaults={
                'business_id': customer.business_id,
                'customer_id': customer.pk,
                'entry_type': 'debit_adjustment',
                'debit': customer.outstanding_amount,
                'credit': 0,
                'reference_type': 'opening_balance',
                'reference_id': str(customer.pk),
                'description': 'Opening balance migrated from Customer.outstanding_amount',
            },
        )

    for supplier in Supplier.objects.filter(outstanding_amount__gt=0):
        SupplierLedger.objects.get_or_create(
            event_key=f'opening:supplier:{supplier.pk}',
            defaults={
                'business_id': supplier.business_id,
                'supplier_id': supplier.pk,
                'entry_type': 'debit_adjustment',
                'debit': supplier.outstanding_amount,
                'credit': 0,
                'reference_type': 'opening_balance',
                'reference_id': str(supplier.pk),
                'description': 'Opening balance migrated from Supplier.outstanding_amount',
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_customerledger_supplierledger_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerledger',
            name='event_key',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='supplierledger',
            name='event_key',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.RunPython(seed_opening_balances, migrations.RunPython.noop),
    ]
