# Generated by Django 4.2.16 on 2026-09-07 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_invoice_payment_status_alter_invoice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorytransaction',
            name='reference_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='reference_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
