# Generated by Django 4.2.16 on 2026-09-07 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_inventorytransaction_reference_id_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='expense_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='invoiceitem',
            constraint=models.CheckConstraint(check=models.Q(('mrp__gte', 0)), name='invoice_item_mrp_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='purchase',
            constraint=models.CheckConstraint(check=models.Q(('total_amount__gte', 0)), name='purchase_total_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='purchase',
            constraint=models.CheckConstraint(check=models.Q(('paid_amount__gte', 0)), name='purchase_paid_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='purchasereturn',
            constraint=models.CheckConstraint(check=models.Q(('debit_amount__gte', 0)), name='purchase_return_debit_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='purchasereturnitem',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gt', 0)), name='purchase_return_item_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='purchasereturnitem',
            constraint=models.CheckConstraint(check=models.Q(('purchase_price__gte', 0)), name='purchase_return_item_price_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='purchasereturnitem',
            constraint=models.CheckConstraint(check=models.Q(('total__gte', 0)), name='purchase_return_item_total_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='salesreturn',
            constraint=models.CheckConstraint(check=models.Q(('refund_amount__gte', 0)), name='sales_return_refund_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='salesreturnitem',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gt', 0)), name='sales_return_item_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='salesreturnitem',
            constraint=models.CheckConstraint(check=models.Q(('unit_price__gte', 0)), name='sales_return_item_price_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='salesreturnitem',
            constraint=models.CheckConstraint(check=models.Q(('total__gte', 0)), name='sales_return_item_total_nonnegative'),
        ),
    ]
