# Generated by Django 4.2.16 on 2026-09-07 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_expense_expense_amount_positive_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='product_stock_nonnegative',
        ),
    ]
