# Generated by Django 4.2.16 on 2026-09-07 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_product_product_stock_nonnegative'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='inventorytransaction',
            name='inventory_before_nonnegative',
        ),
        migrations.RemoveConstraint(
            model_name='inventorytransaction',
            name='inventory_after_nonnegative',
        ),
    ]
