# Generated by Django 4.2.16 on 2026-09-07

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_inventorytransaction_inventory_before_nonnegative_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=api.models.generate_short_link_code, editable=False, max_length=6, unique=True)),
                ('expires_at', models.DateTimeField(default=api.models.default_short_link_expiry)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='short_links', to='api.invoice')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['expires_at'], name='shortlink_expiry_idx')],
            },
        ),
    ]
