# Generated by Django 4.2.16 on 2026-10-01 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_invoice_cancel_reason_invoice_cancelled_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('low_stock', 'Low Stock'), ('invoice_overdue', 'Invoice Overdue'), ('payment_received', 'Payment Received'), ('purchase_order_pending', 'Purchase Order Pending'), ('quotation_expiring', 'Quotation Expiring'), ('batch_expiring', 'Batch Expiring'), ('gst_submission_failed', 'GST Submission Failed'), ('einvoice_failed', 'E-Invoice Failed'), ('eway_bill_expiring', 'E-Way Bill Expiring'), ('approval_required', 'User Action Requiring Approval')], max_length=40)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('danger', 'Danger'), ('success', 'Success')], default='info', max_length=15)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('action_url', models.CharField(blank=True, default='', max_length=255)),
                ('action_label', models.CharField(blank=True, default='View Details', max_length=60)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='active', max_length=20)),
                ('requires_approval', models.BooleanField(default=False)),
                ('actioned_at', models.DateTimeField(blank=True, null=True)),
                ('action_notes', models.TextField(blank=True, default='')),
                ('dedup_key', models.CharField(blank=True, db_index=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actioned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actioned_notifications', to=settings.AUTH_USER_MODEL)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.business')),
                ('read_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='read_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['business', 'is_read', 'created_at'], name='api_notific_busines_4b5479_idx'), models.Index(fields=['business', 'notification_type'], name='api_notific_busines_ab1d0a_idx')],
            },
        ),
    ]
