# Generated by Django 4.2.16 on 2026-10-01 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_invoice_public_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='entity_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
