# Generated by Django 4.2.16 on 2026-10-02 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auditlog_entity_name_auditlog_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('email', 'Email')], default='whatsapp', max_length=20)),
                ('message_type', models.CharField(choices=[('invoice', 'Invoice'), ('payment_reminder', 'Payment Reminder'), ('statement', 'Customer Statement'), ('purchase_confirmation', 'Purchase Confirmation')], max_length=30)),
                ('recipient_name', models.CharField(blank=True, max_length=200)),
                ('recipient_phone', models.CharField(blank=True, max_length=30)),
                ('recipient_email', models.EmailField(blank=True, max_length=254)),
                ('reference_type', models.CharField(blank=True, max_length=30)),
                ('reference_id', models.CharField(blank=True, max_length=100)),
                ('short_url', models.URLField(blank=True, max_length=500)),
                ('content', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='sent', max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('error_message', models.TextField(blank=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.business')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['business', 'reference_type', 'reference_id'], name='api_communi_busines_1a8614_idx'), models.Index(fields=['sent_at'], name='api_communi_sent_at_26a19a_idx')],
            },
        ),
    ]
