# Generated by Django 4.2.16 on 2026-10-02 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_communicationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='place_of_supply',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
